
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DAVID
 */
public class Interfaz2 extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz2
     */
    public Interfaz2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnlistar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtcargar_prof = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        txtRutaarch = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setName("Registro Profesores"); // NOI18N

        btnlistar.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnlistar.setText("2. Lista de docentes");
        btnlistar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlistarActionPerformed(evt);
            }
        });

        btnAgregar.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnAgregar.setText("1. Agregar docente");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        txtcargar_prof.setColumns(20);
        txtcargar_prof.setRows(5);
        jScrollPane1.setViewportView(txtcargar_prof);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setText("Ingrese ruta para Guardar archivo");

        txtRutaarch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRutaarchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(298, 298, 298)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnlistar, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(txtRutaarch, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(txtRutaarch))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnlistar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(250, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 772, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 605, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnlistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlistarActionPerformed
        ListaProfesores lista = new ListaProfesores();
        txtcargar_prof.setText("");
        String datos = lista.leerPofesores();
        this.txtcargar_prof.append(datos);
    }//GEN-LAST:event_btnlistarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
//        ArrayList<Profesor> lista = new ArrayList<>();
        ListaProfesores lista = new ListaProfesores();
        String tipos[] = {"Tiempo Completo", "Medio Tiempo", "Tiempo Parcial"};
                    int tipo = JOptionPane.showOptionDialog(null, "Seleccione el tipo de docente", "TIPO DOCENTE", 0, JOptionPane.QUESTION_MESSAGE, new ImageIcon(), tipos, tipos[0]);
                    String nombres = JOptionPane.showInputDialog("Ingrese el nombre del docente");
                    String apellidos = JOptionPane.showInputDialog("Ingrese el apellido del docente " + nombres);
                    String cedula = JOptionPane.showInputDialog("Ingrese la cedula del docente " + nombres + " " + apellidos);
                    String carrera = JOptionPane.showInputDialog("Ingrese la carrera en la que imparte el/la docente " + nombres + " " + apellidos);
                    
                    if (tipo == 0) {
                        int horasClase = Integer.parseInt(JOptionPane.showInputDialog("Ingrese las horas que imparte el/la docente " + nombres + " " + apellidos + "\n estas deben ser de 3 a 16 horas "));
                        if (horasClase > 2 & horasClase < 17) {
                            lista.agregar(new ProfesorTiempoCompleto(cedula, nombres, apellidos, horasClase, carrera));
                            
                        } else {
                            JOptionPane.showMessageDialog(null, "El docente de tiempo completo debe impartir desde 3 horas hasta 16 horas clase", "ERROR", JOptionPane.ERROR_MESSAGE);
                        }
                    }
                    if (tipo == 1) {
                        int horasClase = Integer.parseInt(JOptionPane.showInputDialog("Ingrese las horas que imparte el/la docente " + nombres + " " + apellidos + "\n estas deben ser 10 horas "));
                        if (horasClase == 10) {
                            lista.agregar(new ProfesorMedioTiempo(cedula, nombres, apellidos, horasClase, carrera));
                        } else {
                            JOptionPane.showMessageDialog(null, "El docente de medio tiempo debe impartir 10 horas clase", "ERROR", JOptionPane.ERROR_MESSAGE);
                        }
                    }
                    if (tipo == 2) {
                        int horasSemanales = Integer.parseInt(JOptionPane.showInputDialog("Ingrese las horas semanales de trabajo del docente " + nombres + " " + apellidos + "\n estas deben ser menos de 20 horas Semanales"));
                        int horasClase = Integer.parseInt(JOptionPane.showInputDialog("Ingrese las horas que imparte el/la docente " + nombres + " " + apellidos + "\n estas deben ser de 2 a 9 horas "));
                        if ((horasClase > 1 & horasClase < 10) & horasSemanales < 20) {
                            lista.agregar(new ProfesorTiempoParcial(cedula, nombres, apellidos, horasClase, carrera, horasSemanales));
                        } else {
                            JOptionPane.showMessageDialog(null, "El docente de tiempo parcial trabaja menos de 20 horas a la semana y debe impartir de 2 a 9 horas clase.", "ERROR", JOptionPane.ERROR_MESSAGE);
                        }
  
                    }
                    lista.grabar();
                    JOptionPane.showMessageDialog(null, "PROFESOR AGREGADO!!!");
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void txtRutaarchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRutaarchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRutaarchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnlistar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtRutaarch;
    private javax.swing.JTextArea txtcargar_prof;
    // End of variables declaration//GEN-END:variables
}
